#pragma once

#include "antonio-semibold20.h"
#include "antonio-semibold30.h"
#include "antonio-semibold40.h"
#include "antonio-semibold90.h"
#include "librefranklin-bold40.h"
#include "librefranklin-semibold29.h"
#include "sats-symbol.h"

#include "LibreFranklin10.h"
#include "LibreFranklin12.h"
#include "LibreFranklin15.h"
#include "LibreFranklin20.h"
#include "LibreFranklin25.h"
#include "LibreFranklin30.h"

#include "orangeclock-icons10.h"
#include "orangeclock-icons11.h"
#include "orangeclock-icons12.h"
#include "orangeclock-icons14.h"
#include "orangeclock-icons15.h"
#include "orangeclock-icons19.h"
#include "orangeclock-icons20.h"
#include "orangeclock-icons25.h"
#include "orangeclock-icons35.h"

// #include "oswald-20.h"
// #include "oswald-30.h"
// #include "oswald-90.h"
// #include "ubuntu-italic40.h"
// #include "ubuntu-italic60.h"
// #include "ubuntu-italic70.h"